services:
  - type: web
    name: sara-compliment-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BOT_TOKEN
        value: "8533622514:AAG-3A6UYXibeRyp6-HCh2pkFb4Tt_OWAjA"
      - key: SARA_CHAT_ID
        value: "1924079795"
      - key: SARA_USERNAME
        value: "@swinsara"
